<?php
return[
'Email'=>'البريد الالكتروني',
'Password'=>'كلمة السر',
'login'=>'تسجيل الدخول',
'Don\'t have account'=>'ليس لديك حساب',
'sign up'=>'انشاء حساب',
'Sign Up'=>'انشاء حساب',
'sign Up'=>'انشاء حساب',
'Sign up'=>'انشاء حساب',
'Full Name'=>'الاسم الكامل',
'Phone Number'=>'رقم الهاتف',
'location-street-building NO.'=>'المنطقة-الشارع-رقم العمارة',
'Have Account'=>'لديك حساب',
'Home'=>'الرئيسية',
'Products'=>'المنتجات',
'Contact'=>'تواصل معنا',
'Contact us'=>'تواصل معنا',
'My Profile'=>'الملف الشخصي',
'Profile'=>'الملف الشخصي',
'Product Details'=>'تفاصيل المنتج',
'Order Details'=>'تفاصيل الطلب',
'Order Confirmation'=>'تأكيد الطلب',
'show order products'=>'عرض تفاصيل الطلب',
'logout'=>'تسجيل الخروج',
'language'=>'اللغة',

'out of stock'=>'نفذ من المخزن',

'Tulip Care'=>'توليب',
'Woman Care'=>'العناية بالمرأة',
'Baby Care'=>'العناية بالطفل',
'Personal Care'=>'العناية الشخصية',
'Hair Care'=>'العناية بالشعر',
'Skin Care'=>'العناية بالبشرة',
'Food Suppliments'=>'المكملات الغذائية',
'Food Supplements'=>'المكملات الغذائية',
'add to cart'=>'أصف الى السلة',
'Next'=>'التالي',
'Shopping Cart'=>'عربة التسوق',
'sub Total'=>'المجموع الفرعي',
'SubTotal'=>'المجموع الفرعي',
'Delivery'=>'التوصيل',
'Total'=>'المجموع الكلي',
'Confirm Order'=>'تثبيت الطلب',
'confirm'=>'تأكيد',
'Confirm'=>'تأكيد',
'order placed successfully'=>'تم وضع الطلب بنجاح',
'Personal Info'=>'المعلومات الشخصية',
'My Orders'=>'طلباتي',
'Orders'=>'الطلبات',
'Change Info'=>'تعديل المعلومات',
'Exit'=>'الغاء',
'save'=>'حفظ',
'order No'=>'رقم الطلب',
'orderNo'=>'رقم الطلب',

'Status'=>'الحالة',
'Date'=>'تاريخ الطلب',
'order Date'=>'تاريخ الطلب',
'show order details'=>'عرض تفاصيل الطلب',
'orderDate'=>'تاريخ الطلب',
'showOrderOetails'=>'عرض تفاصيل الطلب',
'Add Products'=>'اضافة منتجات',
'Edit Products'=>'تعديل المنتجات',
'Admin Profile'=>'الملف الشخصي',
'Change Status'=>'تغيير الحالة',
'Order #'=>' الطلب',

'product Name'=>'اسم المنتج',
'Product Name'=>'اسم المنتج',

'Quantity'=>'الكمية',
'Price'=>'السعر',
'username'=>'اسم المسنخدم',
'Username'=>'الاسم',
'Location'=>'العنوان',

'Category'=>'القسم',
'Description'=>'الوصف',
'price after disccount'=>'السعر بعد الخصم',
'product Image'=>'صورة المنتج',
'Add Product'=>'اضافة المنتج',
'Shampoo'=>'شامبو',
'Hair Coloring'=>'صبغات الشعر',
'Hair Treatments & oils'=>'علاجات وزيوت الشعر',
'Hair Brushes'=>'فرشاة الشعر',
'Body Care'=>'العناية بالجسم',
'Face Care'=>'العناية بالوجه',
'Foot,Hand,Nails Care'=>'العناية بالقدم , اليدين, الاظافر',
'Sunblock & Tanning products'=>'واقي الشمس ومنتجات التسمير',
'Eyes & Lips'=>'العيون والشفاه',
'Tools & Toys'=>'الادوات والالعاب',
'body care & diapers'=>'الحفاضات والعناية بالجسم',
'Food & Milk'=>'الغذاء والحليب',
'Edit Product'=>'تعديل المنتج',
'Edit Product Details'=>'تعديل تفاصيل المنتج',

'UserOrders'=>'الطلبات',
'Admin Home'=>'الصفحة الرئيسية',
'Preparing'=>'قيد التجهيز',
'Delivering'=>'قيد التوصيل',
'Delivered'=>'تم التوصيل'
];



 ?>
