<?php
return[
'Email'=>'Email',
'Password'=>'Password',
'login'=>'login',
'Don\'t have account'=>'Don\'t have account',
'sign up'=>'sign Up',
'Sign Up'=>'Sign Up',
'sign Up'=>'sign Up',
'Sign up'=>'Sign up',
'Full Name'=>'Full Name',
'Phone Number'=>'Phone Number',
'location-street-building NO.'=>'location-street-building NO.',
'Have Account'=>'Have Account',
'Home'=>'Home',
'Products'=>'Products',
'Contact'=>'Contact',
'Contact us'=>'Contact us',
'My Profile'=>'My Profile',
'Profile'=>'Personal Profile',
'Product Details'=>'Product Details',
'Order Details'=>'Order Details',
'Order Confirmation'=>'Order Confirmation',
'show order products'=>'show order products',
'logout'=>'logout',
'language'=>'language',
'out of stock'=>'out of stock',
'Tulip Care'=>'Tulip Care',
'Woman Care'=>'Woman Care',
'Baby Care'=>'Baby Care',
'Personal Care'=>'Personal Care',
'Hair Care'=>'Hair Care',
'Skin Care'=>'Skin Care',
'Food Suppliments'=>'Food Suppliments',
'Food Supplements'=>'Food Supplements',
'add to cart'=>'add to cart',
'Next'=>'Next',
'Shopping Cart'=>'Shopping Cart',
'sub Total'=>'sub Total',
'SubTotal'=>'SubTotal',
'Delivery'=>'Delivery',
'Total'=>'Total',
'Confirm Order'=>'Confirm Order',
'confirm'=>'confirm',
'Confirm'=>'Confirm',
'order placed successfully'=>'order placed successfully',
'Personal Info'=>'Personal Info',
'My Orders'=>'My Orders',
'Orders'=>'Orders',
'Change Info'=>'Change Info',
'Exit'=>'Exit',
'save'=>'save',
'order No'=>'order No.',
'orderNo'=>'order No.',

'Status'=>'Status',
'Date'=>'Date',
'order Date'=>'order Date',
'orderDate'=>'order Date',
'showOrderOetails'=>'show order details',
'show order details'=>'show order details',

'Add Products'=>'Add Products',
'Edit Products'=>'Edit Products',
'Admin Profile'=>'Admin Profile',
'Change Status'=>'Change Status',

'Order #'=>'Order #',

'product Name'=>'product Name',
'Product Name'=>'Product Name',

'Quantity'=>'Quantity',
'Price'=>'Price',
'username'=>'username',
'Username'=>'Username',

'Location'=>'Location',

'Category'=>'Category',
'Description'=>'Description',
'price after disccount'=>'price after disccount',
'product Image'=>'product Image',
'Add Product'=>'Add Product',
'Shampoo'=>'Shampoo',
'Hair Coloring'=>'Hair Coloring',
'Hair Treatments & oils'=>'Hair Treatments & oils',
'Hair Brushes'=>'Hair Brushes',
'Body Care'=>'Body Care',
'Face Care'=>'Face Care',
'Foot,Hand,Nails Care'=>'Foot,Hand,Nails Care',
'Sunblock & Tanning products'=>'Sunblock & Tanning products',
'Eyes & Lips'=>'Eyes & Lips',
'Tools & Toys'=>'Tools & Toys',
'body care & diapers'=>'body care & diapers',
'Food & Milk'=>'Food & Milk',
'Edit Product'=>'Edit Product',
'Edit Product Details'=>'Edit Product Details',
'UserOrders'=>'UserOrders' ,
'Admin Home'=>'Admin Home',
'Preparing'=>'Preparing',
'Delivering'=>'Delivering',
'Delivered'=>'Delivered'
];


 ?>
